using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Media;
using WpfColorHelper;

namespace CsInlineColorViz;

public static class ColorListHelper
{
	// Note that SystemColors are KnownColors
	// Also note that System.Windows.SystemColors are the same as Systmem.Drawing.SystemColors, but with "Color" on the end
	public static IEnumerable<System.Drawing.Color> SystemColorsAlphabetically()
	{
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveBorder);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveCaption);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveCaptionText);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AppWorkspace);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonFace);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonHighlight);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonShadow);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Control);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlDark);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlDarkDark);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlLight);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlLightLight);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlText);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Desktop);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GradientActiveCaption);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GradientInactiveCaption);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Highlight);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HighlightText);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HotTrack);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveBorder);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveCaption);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveCaptionText);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Info);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InfoText);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Menu);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuBar);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuHighlight);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuText);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ScrollBar);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Window);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WindowFrame);
		yield return System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WindowText);
	}

	// TODO: might be nice to add a test that this produces the same as
	// Enum.GetValues(typeof(System.ConsoleColor)).Cast<object>().ToList().OrderBy(o => o.ToString()).Select(o => o.ToString())
	// [In theory] hardcoding this list to save work at runtime.
	public static IEnumerable<string> ConsoleColorsNamesAlphabetical()
	{
		yield return nameof(System.ConsoleColor.Black);
		yield return nameof(System.ConsoleColor.Blue);
		yield return nameof(System.ConsoleColor.Cyan);
		yield return nameof(System.ConsoleColor.DarkBlue);
		yield return nameof(System.ConsoleColor.DarkCyan);
		yield return nameof(System.ConsoleColor.DarkGray);
		yield return nameof(System.ConsoleColor.DarkGreen);
		yield return nameof(System.ConsoleColor.DarkMagenta);
		yield return nameof(System.ConsoleColor.DarkRed);
		yield return nameof(System.ConsoleColor.DarkYellow);
		yield return nameof(System.ConsoleColor.Gray);
		yield return nameof(System.ConsoleColor.Green);
		yield return nameof(System.ConsoleColor.Magenta);
		yield return nameof(System.ConsoleColor.Red);
		yield return nameof(System.ConsoleColor.White);
		yield return nameof(System.ConsoleColor.Yellow);
	}

	public static IEnumerable<System.Drawing.Color> SystemDrawingColorsAlphabetical()
	{
		yield return System.Drawing.Color.AliceBlue;
		yield return System.Drawing.Color.AntiqueWhite;
		yield return System.Drawing.Color.Aqua;
		yield return System.Drawing.Color.Aquamarine;
		yield return System.Drawing.Color.Azure;
		yield return System.Drawing.Color.Beige;
		yield return System.Drawing.Color.Bisque;
		yield return System.Drawing.Color.Black;
		yield return System.Drawing.Color.BlanchedAlmond;
		yield return System.Drawing.Color.Blue;
		yield return System.Drawing.Color.BlueViolet;
		yield return System.Drawing.Color.Brown;
		yield return System.Drawing.Color.BurlyWood;
		yield return System.Drawing.Color.CadetBlue;
		yield return System.Drawing.Color.Chartreuse;
		yield return System.Drawing.Color.Chocolate;
		yield return System.Drawing.Color.Coral;
		yield return System.Drawing.Color.CornflowerBlue;
		yield return System.Drawing.Color.Cornsilk;
		yield return System.Drawing.Color.Crimson;
		yield return System.Drawing.Color.Cyan;
		yield return System.Drawing.Color.DarkBlue;
		yield return System.Drawing.Color.DarkCyan;
		yield return System.Drawing.Color.DarkGoldenrod;
		yield return System.Drawing.Color.DarkGray;
		yield return System.Drawing.Color.DarkGreen;
		yield return System.Drawing.Color.DarkKhaki;
		yield return System.Drawing.Color.DarkMagenta;
		yield return System.Drawing.Color.DarkOliveGreen;
		yield return System.Drawing.Color.DarkOrange;
		yield return System.Drawing.Color.DarkOrchid;
		yield return System.Drawing.Color.DarkRed;
		yield return System.Drawing.Color.DarkSalmon;
		yield return System.Drawing.Color.DarkSeaGreen;
		yield return System.Drawing.Color.DarkSlateBlue;
		yield return System.Drawing.Color.DarkSlateGray;
		yield return System.Drawing.Color.DarkTurquoise;
		yield return System.Drawing.Color.DarkViolet;
		yield return System.Drawing.Color.DeepPink;
		yield return System.Drawing.Color.DeepSkyBlue;
		yield return System.Drawing.Color.DimGray;
		yield return System.Drawing.Color.DodgerBlue;
		yield return System.Drawing.Color.Firebrick;
		yield return System.Drawing.Color.FloralWhite;
		yield return System.Drawing.Color.ForestGreen;
		yield return System.Drawing.Color.Fuchsia;
		yield return System.Drawing.Color.Gainsboro;
		yield return System.Drawing.Color.GhostWhite;
		yield return System.Drawing.Color.Gold;
		yield return System.Drawing.Color.Goldenrod;
		yield return System.Drawing.Color.Gray;
		yield return System.Drawing.Color.Green;
		yield return System.Drawing.Color.GreenYellow;
		yield return System.Drawing.Color.Honeydew;
		yield return System.Drawing.Color.HotPink;
		yield return System.Drawing.Color.IndianRed;
		yield return System.Drawing.Color.Indigo;
		yield return System.Drawing.Color.Ivory;
		yield return System.Drawing.Color.Khaki;
		yield return System.Drawing.Color.Lavender;
		yield return System.Drawing.Color.LavenderBlush;
		yield return System.Drawing.Color.LawnGreen;
		yield return System.Drawing.Color.LemonChiffon;
		yield return System.Drawing.Color.LightBlue;
		yield return System.Drawing.Color.LightCoral;
		yield return System.Drawing.Color.LightCyan;
		yield return System.Drawing.Color.LightGreen;
		yield return System.Drawing.Color.LightPink;
		yield return System.Drawing.Color.LightSalmon;
		yield return System.Drawing.Color.LightSeaGreen;
		yield return System.Drawing.Color.LightSkyBlue;
		yield return System.Drawing.Color.LightSlateGray;
		yield return System.Drawing.Color.LightSteelBlue;
		yield return System.Drawing.Color.LightYellow;
		yield return System.Drawing.Color.Lime;
		yield return System.Drawing.Color.LimeGreen;
		yield return System.Drawing.Color.Linen;
		yield return System.Drawing.Color.Magenta;
		yield return System.Drawing.Color.Maroon;
		yield return System.Drawing.Color.MediumAquamarine;
		yield return System.Drawing.Color.MediumBlue;
		yield return System.Drawing.Color.MediumOrchid;
		yield return System.Drawing.Color.MediumPurple;
		yield return System.Drawing.Color.MediumSeaGreen;
		yield return System.Drawing.Color.MediumSlateBlue;
		yield return System.Drawing.Color.MediumSpringGreen;
		yield return System.Drawing.Color.MediumTurquoise;
		yield return System.Drawing.Color.MediumVioletRed;
		yield return System.Drawing.Color.MidnightBlue;
		yield return System.Drawing.Color.MintCream;
		yield return System.Drawing.Color.MistyRose;
		yield return System.Drawing.Color.Moccasin;
		yield return System.Drawing.Color.NavajoWhite;
		yield return System.Drawing.Color.Navy;
		yield return System.Drawing.Color.OldLace;
		yield return System.Drawing.Color.Olive;
		yield return System.Drawing.Color.OliveDrab;
		yield return System.Drawing.Color.Orange;
		yield return System.Drawing.Color.OrangeRed;
		yield return System.Drawing.Color.Orchid;
		yield return System.Drawing.Color.PaleGoldenrod;
		yield return System.Drawing.Color.PaleGreen;
		yield return System.Drawing.Color.PaleTurquoise;
		yield return System.Drawing.Color.PaleVioletRed;
		yield return System.Drawing.Color.PapayaWhip;
		yield return System.Drawing.Color.PeachPuff;
		yield return System.Drawing.Color.Peru;
		yield return System.Drawing.Color.Pink;
		yield return System.Drawing.Color.Plum;
		yield return System.Drawing.Color.PowderBlue;
		yield return System.Drawing.Color.Purple;
		yield return System.Drawing.Color.Red;
		yield return System.Drawing.Color.RosyBrown;
		yield return System.Drawing.Color.RoyalBlue;
		yield return System.Drawing.Color.SaddleBrown;
		yield return System.Drawing.Color.Salmon;
		yield return System.Drawing.Color.SandyBrown;
		yield return System.Drawing.Color.SeaGreen;
		yield return System.Drawing.Color.SeaShell;
		yield return System.Drawing.Color.Sienna;
		yield return System.Drawing.Color.Silver;
		yield return System.Drawing.Color.SkyBlue;
		yield return System.Drawing.Color.SlateBlue;
		yield return System.Drawing.Color.SlateGray;
		yield return System.Drawing.Color.Snow;
		yield return System.Drawing.Color.SpringGreen;
		yield return System.Drawing.Color.SteelBlue;
		yield return System.Drawing.Color.Tan;
		yield return System.Drawing.Color.Teal;
		yield return System.Drawing.Color.Thistle;
		yield return System.Drawing.Color.Tomato;
		yield return System.Drawing.Color.Transparent;
		yield return System.Drawing.Color.Turquoise;
		yield return System.Drawing.Color.Violet;
		yield return System.Drawing.Color.Wheat;
		yield return System.Drawing.Color.White;
		yield return System.Drawing.Color.WhiteSmoke;
		yield return System.Drawing.Color.Yellow;
		yield return System.Drawing.Color.YellowGreen;
	}

	public static IEnumerable<System.Drawing.Color> SystemDrawingColorsSpectrum()
	{
		yield return System.Drawing.Color.Tan;
		yield return System.Drawing.Color.RosyBrown;
		yield return System.Drawing.Color.Sienna;
		yield return System.Drawing.Color.SaddleBrown;
		yield return System.Drawing.Color.DarkRed;
		yield return System.Drawing.Color.Maroon;
		yield return System.Drawing.Color.Brown;
		yield return System.Drawing.Color.Firebrick;
		yield return System.Drawing.Color.Crimson;
		yield return System.Drawing.Color.Red;
		yield return System.Drawing.Color.OrangeRed;
		yield return System.Drawing.Color.IndianRed;
		yield return System.Drawing.Color.Tomato;
		yield return System.Drawing.Color.Chocolate;
		yield return System.Drawing.Color.DarkSalmon;
		yield return System.Drawing.Color.Coral;
		yield return System.Drawing.Color.Salmon;
		yield return System.Drawing.Color.LightCoral;
		yield return System.Drawing.Color.Peru;
		yield return System.Drawing.Color.DarkOrange;
		yield return System.Drawing.Color.SandyBrown;
		yield return System.Drawing.Color.LightSalmon;
		yield return System.Drawing.Color.Orange;
		yield return System.Drawing.Color.Goldenrod;
		yield return System.Drawing.Color.BurlyWood;
		yield return System.Drawing.Color.DarkGoldenrod;
		yield return System.Drawing.Color.DarkKhaki;
		yield return System.Drawing.Color.AntiqueWhite;
		yield return System.Drawing.Color.Beige;
		yield return System.Drawing.Color.Cornsilk;
		yield return System.Drawing.Color.OldLace;
		yield return System.Drawing.Color.Linen;
		yield return System.Drawing.Color.Honeydew;
		yield return System.Drawing.Color.LightYellow;
		yield return System.Drawing.Color.LemonChiffon;
		yield return System.Drawing.Color.BlanchedAlmond;
		yield return System.Drawing.Color.Bisque;
		yield return System.Drawing.Color.Wheat;
		yield return System.Drawing.Color.Moccasin;
		yield return System.Drawing.Color.NavajoWhite;
		yield return System.Drawing.Color.PeachPuff;
		yield return System.Drawing.Color.PapayaWhip;
		yield return System.Drawing.Color.PaleGoldenrod;
		yield return System.Drawing.Color.Khaki;
		yield return System.Drawing.Color.Gold;
		yield return System.Drawing.Color.Yellow;
		yield return System.Drawing.Color.GreenYellow;
		yield return System.Drawing.Color.YellowGreen;
		yield return System.Drawing.Color.Chartreuse;
		yield return System.Drawing.Color.LawnGreen;
		yield return System.Drawing.Color.PaleGreen;
		yield return System.Drawing.Color.LightGreen;
		yield return System.Drawing.Color.MediumSpringGreen;
		yield return System.Drawing.Color.SpringGreen;
		yield return System.Drawing.Color.Lime;
		yield return System.Drawing.Color.LimeGreen;
		yield return System.Drawing.Color.MediumSeaGreen;
		yield return System.Drawing.Color.ForestGreen;
		yield return System.Drawing.Color.Green;
		yield return System.Drawing.Color.DarkGreen;
		yield return System.Drawing.Color.SeaGreen;
		yield return System.Drawing.Color.DarkSeaGreen;
		yield return System.Drawing.Color.OliveDrab;
		yield return System.Drawing.Color.Olive;
		yield return System.Drawing.Color.DarkOliveGreen;
		yield return System.Drawing.Color.Teal;
		yield return System.Drawing.Color.DarkCyan;
		yield return System.Drawing.Color.CadetBlue;
		yield return System.Drawing.Color.LightSeaGreen;
		yield return System.Drawing.Color.MediumAquamarine;
		yield return System.Drawing.Color.MediumTurquoise;
		yield return System.Drawing.Color.Turquoise;
		yield return System.Drawing.Color.Aquamarine;
		yield return System.Drawing.Color.PaleTurquoise;
		yield return System.Drawing.Color.LightBlue;
		yield return System.Drawing.Color.LightCyan;
		yield return System.Drawing.Color.PowderBlue;
		yield return System.Drawing.Color.SkyBlue;
		yield return System.Drawing.Color.LightSkyBlue;
		yield return System.Drawing.Color.LightSteelBlue;
		yield return System.Drawing.Color.DeepSkyBlue;
		yield return System.Drawing.Color.Aqua;
		yield return System.Drawing.Color.Cyan;
		yield return System.Drawing.Color.DarkTurquoise;
		yield return System.Drawing.Color.DodgerBlue;
		yield return System.Drawing.Color.CornflowerBlue;
		yield return System.Drawing.Color.SteelBlue;
		yield return System.Drawing.Color.RoyalBlue;
		yield return System.Drawing.Color.MediumBlue;
		yield return System.Drawing.Color.Blue;
		yield return System.Drawing.Color.DarkBlue;
		yield return System.Drawing.Color.Navy;
		yield return System.Drawing.Color.MidnightBlue;
		yield return System.Drawing.Color.DarkSlateBlue;
		yield return System.Drawing.Color.Indigo;
		yield return System.Drawing.Color.SlateBlue;
		yield return System.Drawing.Color.MediumSlateBlue;
		yield return System.Drawing.Color.MediumPurple;
		yield return System.Drawing.Color.BlueViolet;
		yield return System.Drawing.Color.DarkViolet;
		yield return System.Drawing.Color.DarkOrchid;
		yield return System.Drawing.Color.Purple;
		yield return System.Drawing.Color.DarkMagenta;
		yield return System.Drawing.Color.MediumOrchid;
		yield return System.Drawing.Color.Magenta;
		yield return System.Drawing.Color.Fuchsia;
		yield return System.Drawing.Color.Orchid;
		yield return System.Drawing.Color.Violet;
		yield return System.Drawing.Color.Plum;
		yield return System.Drawing.Color.PaleVioletRed;
		yield return System.Drawing.Color.MediumVioletRed;
		yield return System.Drawing.Color.DeepPink;
		yield return System.Drawing.Color.HotPink;
		yield return System.Drawing.Color.Thistle;
		yield return System.Drawing.Color.LightPink;
		yield return System.Drawing.Color.Pink;
		yield return System.Drawing.Color.MistyRose;
		yield return System.Drawing.Color.Lavender;
		yield return System.Drawing.Color.LavenderBlush;
		yield return System.Drawing.Color.AliceBlue;
		yield return System.Drawing.Color.Azure;
		yield return System.Drawing.Color.FloralWhite;
		yield return System.Drawing.Color.WhiteSmoke;
		yield return System.Drawing.Color.SeaShell;
		yield return System.Drawing.Color.Ivory;
		yield return System.Drawing.Color.MintCream;
		yield return System.Drawing.Color.Snow;
		yield return System.Drawing.Color.White;
		yield return System.Drawing.Color.GhostWhite;
		yield return System.Drawing.Color.Gainsboro;
		yield return System.Drawing.Color.Silver;
		yield return System.Drawing.Color.DarkGray;
		yield return System.Drawing.Color.Gray;
		yield return System.Drawing.Color.DimGray;
		yield return System.Drawing.Color.LightSlateGray;
		yield return System.Drawing.Color.SlateGray;
		yield return System.Drawing.Color.DarkSlateGray;
		yield return System.Drawing.Color.Black;
		yield return System.Drawing.Color.Transparent;
	}

	// This was created from : https://github.com/maddymontaquila/funcolors/blob/main/FunColor.cs
	// Last updated 9-dec-2024 (5b11965)
	public static IEnumerable<(string Name, Color Color)> FunColors()
	{
		yield return ("DotNetPurple2024", (Color)ColorConverter.ConvertFromString("#FF512BD4"));
		yield return ("XamarinBlue2011", (Color)ColorConverter.ConvertFromString("#FF5596D8"));
		yield return ("AndroidBotGreen2024", (Color)ColorConverter.ConvertFromString("#FFA7CD45"));
		yield return ("RubberDuckYellow", (Color)ColorConverter.ConvertFromString("#FFFFD700"));
		yield return ("GameBoyGreen", (Color)ColorConverter.ConvertFromString("#FF9BBC0F"));
		yield return ("BarbiePink", (Color)ColorConverter.ConvertFromString("#FFDA1884"));
		yield return ("PotatoHeadBrown", (Color)ColorConverter.ConvertFromString("#FF8B4513"));
		yield return ("TickleMeElmoRed", (Color)ColorConverter.ConvertFromString("#FFFF3F3F"));
		yield return ("LegoRed", (Color)ColorConverter.ConvertFromString("#FFB40000"));
		yield return ("HotWheelsBlue", (Color)ColorConverter.ConvertFromString("#FF005BAC"));
		yield return ("NerfOrange", (Color)ColorConverter.ConvertFromString("#FFFF6F00"));
		yield return ("PlayDohYellow", (Color)ColorConverter.ConvertFromString("#FFFBE870"));
		yield return ("MyLittlePonyPurple", (Color)ColorConverter.ConvertFromString("#FFDDA0DD"));
		yield return ("TransformersSilver", (Color)ColorConverter.ConvertFromString("#FFC0C0C0"));
		yield return ("GIJoeGreen", (Color)ColorConverter.ConvertFromString("#FF4B5320"));
		yield return ("PowerRangersRed", (Color)ColorConverter.ConvertFromString("#FFFF0000"));
		yield return ("TeenageMutantNinjaTurtlesGreen", (Color)ColorConverter.ConvertFromString("#FF008000"));
		yield return ("CareBearsRainbow", (Color)ColorConverter.ConvertFromString("#FFFF69B4"));
		yield return ("AppleIIBeige", (Color)ColorConverter.ConvertFromString("#FFD3D3D3"));
		yield return ("Commodore64Brown", (Color)ColorConverter.ConvertFromString("#FF6C4F3D"));
		yield return ("Atari800Blue", (Color)ColorConverter.ConvertFromString("#FF0057A0"));
		yield return ("IBMPCGray", (Color)ColorConverter.ConvertFromString("#FF808080"));
		yield return ("TRS80Silver", (Color)ColorConverter.ConvertFromString("#FFC0C0C0"));
		yield return ("ZXSpectrumBlack", (Color)ColorConverter.ConvertFromString("#FF000000"));
		yield return ("AmigaWhite", (Color)ColorConverter.ConvertFromString("#FFFFFFFF"));
		yield return ("MSXBlue", (Color)ColorConverter.ConvertFromString("#FF0000FF"));
		yield return ("BratSummer", (Color)ColorConverter.ConvertFromString("#FF8ACE00"));
		yield return ("BratAutumn", (Color)ColorConverter.ConvertFromString("#FFFF8C00"));
		yield return ("NeonElectricBlue", (Color)ColorConverter.ConvertFromString("#FF154FEE"));
		yield return ("NeonVividMagenta", (Color)ColorConverter.ConvertFromString("#FFFF08FC"));
		yield return ("PukePink", (Color)ColorConverter.ConvertFromString("#FFFF3AC6"));
		yield return ("MushyPeas", (Color)ColorConverter.ConvertFromString("#FF5FA41C"));
		yield return ("PainfulRed", (Color)ColorConverter.ConvertFromString("#FFFF1A00"));
		yield return ("ShrekGreen", (Color)ColorConverter.ConvertFromString("#FF009B00"));
	}
}
