// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CsInlineColorViz
{
    internal sealed partial class Vsix
    {
        public const string Id = "CsColorViz.6b864116-c092-4b7a-aad8-34239a7bbe70";
        public const string Name = "C# Color Vizualizer";
        public const string Description = @"See samples of the colors you use within your C# code.  ";
        public const string Language = "en-US";
        public const string Version = "2.0.0";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
